---
collections:
  #- name: community.general
  - name: ansible.windows
    source: https://ec2-18-183-16-137.ap-northeast-1.compute.amazonaws.com/pulp_ansible/galaxy/rh-certified/
    #https://ec2-18-183-16-137.ap-northeast-1.compute.amazonaws.com/api/galaxy/content/rh-certified/ 
    #https://gateway/pulp_ansible/galaxy/rh-certified/　
