---
- name: Listen for events on a webhook
  hosts: all
  vars:
    ansible_user: admin
    ansible_password: redhat
  sources:   
    - name: Wait for Webhook Message
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
