---
- name: Listen for events on kafka
  hosts: localhost

  sources:
    - name: listen to kafka for events
      ansible.eda.kafka:
        host: 192.168.122.182
        port: 9092
        topic: test-events
        group_id: ansible-eda
  
  rules:  
    - name: Check defined
      condition: event.body.i is defined
      action:
        run_job_template:
          name: eda-test
          organization: Default
        
    - name: Stop
      condition: event.body.stop == true
      action:
        shutdown:
