---
- name: say thanks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set fact for EDA
      ansible.builtin.set_fact:
        cacheable: yes
        fact: 
          say-what: "this is a set_fact from say-what" #"this is a set_fact from a Controller Job Template"
